name: yabause-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 'v1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Sega Saturn emulator
description: |
  The Sega Saturn emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  yabause_icon.png
title: Yabause

apps:
  yabause:
    command: yabause
parts:
  yabause:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      yabause: build/
      yabause.1: man/man1/

architectures:
  - build-on: amd64

